import React from 'react';
import Navigation from '../components/Navigation';
import Logo from '../components/Logo';
const About = () => {
    return (
        <div>
            <Logo />
            <Navigation />
           <h1>A propos</h1> 
           <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Iure consectetur et aliquid laudantium libero quaerat! Necessitatibus sequi assumenda, molestiae itaque eligendi error beatae reprehenderit laboriosam sed sunt voluptatum amet nulla a minima nesciunt eaque dolorem provident expedita. Veritatis laudantium natus quo, id veniam architecto obcaecati asperiores excepturi voluptas iusto porro corrupti, explicabo, error magni consequuntur. Quis adipisci amet in repudiandae voluptatum, est libero nam deleniti natus ut eveniet, excepturi odit, harum minima. Consectetur impedit, veritatis doloribus officia commodi dicta laudantium, excepturi porro a minus tenetur assumenda ea consequuntur harum sed modi similique cumque quod esse quas quam ipsa! Voluptatem molestias illo nemo autem amet molestiae deleniti facilis voluptate recusandae eligendi nam distinctio quae, error veniam corporis velit at odit laudantium temporibus necessitatibus. Eius, molestias? Eligendi possimus officia, dolore facere fugit esse. Non nisi doloribus obcaecati recusandae, provident minus perferendis debitis. Omnis sint porro quis voluptate? Quas iure quia eaque magni molestiae eius quisquam delectus accusamus impedit quod quos repellat facere molestias reprehenderit, enim voluptatibus, eveniet laboriosam corrupti, sequi fugiat magnam? Accusamus reiciendis accusantium nobis, deleniti nam ad labore? Temporibus et nulla tempore tenetur velit tempora eaque deserunt ad magni. Quibusdam debitis mollitia nam labore dolore officia doloremque nesciunt saepe laudantium?</p>
           <br />
           <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde omnis modi quasi, minima, ipsam praesentium ipsa doloribus iure temporibus quis neque, amet explicabo esse voluptates. Repellendus distinctio quos dolores, ullam, at ipsum odit, perferendis saepe doloremque eos illo vero mollitia fugiat esse cumque eius obcaecati illum quo animi alias quod? Similique, eligendi asperiores perferendis, voluptas deserunt illum ad assumenda modi repellat possimus sunt. Distinctio iste veniam sint facere recusandae veritatis dolorem! Architecto distinctio officia facere sequi unde inventore vitae, similique corporis eum perferendis animi, nobis esse doloribus cupiditate, repellat exercitationem porro numquam veritatis necessitatibus! Animi, enim rerum, quam placeat deleniti facere magni reiciendis alias ullam eius, totam in harum molestias aliquam hic voluptatem nisi. Incidunt accusamus, possimus quasi impedit atque sequi enim, nisi et iusto vero officia ut inventore nihil nemo aut mollitia velit eos dolore! Libero, sunt delectus quasi perferendis doloremque, voluptas molestiae minus necessitatibus, provident perspiciatis optio nisi repellat laudantium. Illum modi dolores ullam enim omnis quasi laborum laudantium necessitatibus distinctio, nam id ex reiciendis excepturi eveniet vel repudiandae, qui aspernatur? Voluptatum doloremque eos, facilis sapiente provident voluptatem at ad laboriosam quasi ipsam fugiat, iste minima officiis voluptatibus alias aut, quod excepturi iure! Eum temporibus sit libero doloremque beatae ipsum excepturi eligendi fugiat tempore minima voluptatibus eveniet veniam quia quod asperiores illo ratione dolorum odit, eaque mollitia natus laborum cum exercitationem totam! Neque sequi rerum similique alias ipsum! Expedita, omnis! Libero, reprehenderit quos consequatur aspernatur rerum nesciunt eligendi eos! Nemo tenetur saepe voluptatum distinctio autem harum non libero iure cum minus voluptatem facilis maiores esse similique quibusdam obcaecati doloremque magnam repellat hic modi eius ab, maxime at. Perferendis nulla vel dignissimos, eum accusantium doloribus repellat alias minima illo eius tempora in aut quo labore, veritatis sit, aspernatur est animi autem voluptatem necessitatibus eos? Illum sit in provident autem!</p>
        </div>
    );
};

export default About;